Repository sopt-makers/sopt-operation-backend, pull requests merged in 2023-07, with the labels that each got.

#125 [FEAT] 세션 상세 조회 API
  src/main/java/org/sopt/makers/operation/controller/web/LectureController.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureDetailResponseDTO.java
  src/main/java/org/sopt/makers/operation/service/LectureService.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: sohyeon, size/M, feat

#128 리프레시 테스트용 토큰 만료시간 조정 #112
  src/main/java/org/sopt/makers/operation/security/jwt/JwtAuthenticationFilter.java
  src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenProvider.java
Labels: chore, size/M, yongtaek

#130 [FIX] 출석 점수 갱신 API 수정
  src/main/java/org/sopt/makers/operation/entity/Member.java
Labels: sohyeon, size/S, fix
