Repository sopt-makers/sopt-operation-backend, pull requests merged in 2023-08, with the labels that each got.

#132 [REFACT] 날짜 포맷 리팩토링
  src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
  src/main/java/org/sopt/makers/operation/config/TimezoneConfig.java
  src/main/java/org/sopt/makers/operation/controller/ExceptionController.java
  src/main/java/org/sopt/makers/operation/controller/web/LectureController.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceMemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/MemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/AttendanceVO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/AttendancesStatusVO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureDetailResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureVO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LecturesResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/BaseEntity.java
  src/main/java/org/sopt/makers/operation/entity/SubLecture.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenProvider.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: sohyeon, size/L, fix

#135 [CHORE] 엑세스 토큰 시간 복구 #134
  src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenProvider.java
Labels: chore, yongtaek, size/XS

#141 Sohyeon #139
  src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
  src/main/java/org/sopt/makers/operation/config/TimezoneConfig.java
  src/main/java/org/sopt/makers/operation/controller/ExceptionController.java
  src/main/java/org/sopt/makers/operation/controller/web/AttendanceController.java
  src/main/java/org/sopt/makers/operation/controller/web/LectureController.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceMemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/MemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/AttendanceVO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/AttendancesStatusVO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureDetailResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureVO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LecturesResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/BaseEntity.java
  src/main/java/org/sopt/makers/operation/entity/Member.java
  src/main/java/org/sopt/makers/operation/entity/SubLecture.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/security/jwt/JwtAuthenticationFilter.java
  src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenProvider.java
  src/main/java/org/sopt/makers/operation/service/AttendanceService.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureService.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: size/L
