Repository sopt-makers/sopt-operation-backend, pull requests merged in 2023-04, with the labels that each got.

#22 [FIX] Session Entity명 변경
  src/main/java/org/sopt/makers/operation/entity/Attendance.java
  src/main/java/org/sopt/makers/operation/entity/Lecture.java
  src/main/java/org/sopt/makers/operation/entity/SubAttendance.java
  src/main/java/org/sopt/makers/operation/entity/SubLecture.java
Labels: sohyeon, size/M, fix

#20 [CHORE] 공통 ApiResponse 추가
  src/main/java/org/sopt/makers/operation/common/ApiResponse.java
Labels: sohyeon, chore, size/S

#24 [FEAT] 임원진 로그인 구현, PR반영 #17
  build.gradle
  src/main/java/org/sopt/makers/operation/controller/AdminController.java
  src/main/java/org/sopt/makers/operation/controller/ExceptionController.java
  src/main/java/org/sopt/makers/operation/dto/admin/LoginRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/admin/LoginResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/admin/SignUpRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/admin/SignUpResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/Admin.java
  src/main/java/org/sopt/makers/operation/entity/AdminStatus.java
  src/main/java/org/sopt/makers/operation/entity/Role.java
  src/main/java/org/sopt/makers/operation/exception/AdminFailureException.java
  src/main/java/org/sopt/makers/operation/exception/TokenException.java
  src/main/java/org/sopt/makers/operation/repository/AdminRepository.java
  src/main/java/org/sopt/makers/operation/security/config/SecurityConfig.java
  src/main/java/org/sopt/makers/operation/security/jwt/AdminAuthentication.java
  src/main/java/org/sopt/makers/operation/security/jwt/JwtAuthenticationFilter.java
  src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenProvider.java
  src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenType.java
  src/main/java/org/sopt/makers/operation/service/AdminService.java
  src/main/java/org/sopt/makers/operation/service/AdminServiceImpl.java
  src/main/resources/application.yml
Labels: yongtaek, feat, size/XL

#27 [CHORE] Member Entity 추가
  src/main/java/org/sopt/makers/operation/entity/Gender.java
  src/main/java/org/sopt/makers/operation/entity/Member.java
  src/main/java/org/sopt/makers/operation/entity/ObYb.java
Labels: sohyeon, chore, size/M

#30 [FIX] 세션 엔티티 수정
  src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
  src/main/java/org/sopt/makers/operation/dto/LectureRequestDTO.java
  src/main/java/org/sopt/makers/operation/entity/Attribute.java
  src/main/java/org/sopt/makers/operation/entity/Lecture.java
Labels: size/M

#33 [FEAT] 세션 생성 API 기능 구현
  build.gradle
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/config/JpaQueryFactoryConfig.java
  src/main/java/org/sopt/makers/operation/controller/LectureController.java
  src/main/java/org/sopt/makers/operation/dto/LectureRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/member/MemberSearchCondition.java
  src/main/java/org/sopt/makers/operation/entity/Attendance.java
  src/main/java/org/sopt/makers/operation/entity/Attribute.java
  src/main/java/org/sopt/makers/operation/entity/Member.java
  src/main/java/org/sopt/makers/operation/entity/SubAttendance.java
  src/main/java/org/sopt/makers/operation/entity/SubLecture.java
  src/main/java/org/sopt/makers/operation/entity/lecture/Attribute.java
  src/main/java/org/sopt/makers/operation/entity/lecture/Lecture.java
  src/main/java/org/sopt/makers/operation/repository/AttendanceRepository.java
  src/main/java/org/sopt/makers/operation/repository/SubAttendanceRepository.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureRepository.java
  src/main/java/org/sopt/makers/operation/repository/lecture/SubLectureRepository.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberRepository.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/AdminService.java
  src/main/java/org/sopt/makers/operation/service/AdminServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureService.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
  src/test/java/org/sopt/makers/operation/OperationServerApplicationTests.java
Labels: sohyeon, feat, size/XL

#38 [CHORE] Swagger 추가
  build.gradle
  src/main/java/org/sopt/makers/operation/config/SwaggerConfig.java
  src/main/java/org/sopt/makers/operation/controller/AdminController.java
  src/main/java/org/sopt/makers/operation/controller/HealthCheckController.java
  src/main/java/org/sopt/makers/operation/controller/LectureController.java
Labels: sohyeon, chore, size/L

#39 [FEAT] 세션 상세 조회 기능 구현
  src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/controller/ExceptionController.java
  src/main/java/org/sopt/makers/operation/controller/LectureController.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LecturesResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/SubAttendance.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureService.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: sohyeon, size/L, feat

#43 [FEAT] 출석 점수 변경 기능 구현
  src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/controller/AttendanceController.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/Member.java
  src/main/java/org/sopt/makers/operation/entity/SubAttendance.java
  src/main/java/org/sopt/makers/operation/service/AttendanceService.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
Labels: sohyeon, size/L, feat

#46 [FEAT] 단일 세션 가져오기
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/config/GenerationConfig.java
  src/main/java/org/sopt/makers/operation/controller/AppController.java
  src/main/java/org/sopt/makers/operation/controller/ExceptionController.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureGetResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureGetResponseVO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureResponseType.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureSearchCondition.java
  src/main/java/org/sopt/makers/operation/entity/SubAttendance.java
  src/main/java/org/sopt/makers/operation/exception/LectureException.java
  src/main/java/org/sopt/makers/operation/exception/MemberException.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepository.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureRepository.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberRepository.java
  src/main/java/org/sopt/makers/operation/security/jwt/JwtAuthenticationFilter.java
  src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenProvider.java
  src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenType.java
  src/main/java/org/sopt/makers/operation/service/LectureService.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/MemberService.java
  src/main/java/org/sopt/makers/operation/service/MemberServiceImpl.java
  src/main/resources/application.yml
Labels: yongtaek, size/L, feat

#50 [FEAT] 출석 점수 조회 기능 #49
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/controller/AppController.java
  src/main/java/org/sopt/makers/operation/dto/member/MemberScoreGetResponse.java
Labels: yongtaek, size/S, feat

#53 [FEAT] 유저별 출석 정보 조회: 웹
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/controller/AttendanceController.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceMemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/AttendanceStatus.java
  src/main/java/org/sopt/makers/operation/service/AttendanceService.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
Labels: sohyeon, size/L, feat

#54 [FEAT] 전체 출석 정보 가져오기
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/controller/AppController.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceTotalCountVO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceTotalResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceTotalVO.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepository.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureService.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: yongtaek, size/L, feat

#57 [ADD] 세션별 추가점수 데이터 추가
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceMemberResponseDTO.java
Labels: sohyeon, size/S, add

#59 [FIX] 스웨거 정보 추가
  src/main/java/org/sopt/makers/operation/controller/AppController.java
Labels: chore, yongtaek, size/S

#61 [FEAT] 유저 조회
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/config/SwaggerConfig.java
  src/main/java/org/sopt/makers/operation/controller/AppController.java
  src/main/java/org/sopt/makers/operation/controller/MemberController.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceTotalCountVO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceTotalVO.java
  src/main/java/org/sopt/makers/operation/dto/member/MemberListGetResponse.java
  src/main/java/org/sopt/makers/operation/entity/AttendanceStatus.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberRepository.java
  src/main/java/org/sopt/makers/operation/security/config/SecurityConfig.java
  src/main/java/org/sopt/makers/operation/service/LectureService.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/MemberService.java
  src/main/java/org/sopt/makers/operation/service/MemberServiceImpl.java
Labels: yongtaek, size/L, feat

#55 [FIX] 출석 상태 게산 로직 변경
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/Attendance.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: sohyeon, size/L, fix

#65 [FEAT] 세션 출석 점수 갱신 트리거 구현
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/controller/LectureController.java
  src/main/java/org/sopt/makers/operation/service/LectureService.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: sohyeon, size/M, feat

#69 [FEAT] 유저 출석 점수 갱신 기능 구현
  src/main/java/org/sopt/makers/operation/controller/AttendanceController.java
  src/main/java/org/sopt/makers/operation/entity/Member.java
  src/main/java/org/sopt/makers/operation/service/AttendanceService.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
Labels: sohyeon, size/M, feat

#73 [ADD] 출석 상태 변경 로직 추가
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
  src/main/java/org/sopt/makers/operation/util/Generation32.java
Labels: sohyeon, size/M, add

#72 [FIX] 단일 세미나 로직 변경
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureGetResponseDTO.java
  src/main/java/org/sopt/makers/operation/service/LectureService.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: size/M, yongtaek, fix

#82 [FIX] 회원 파트 필터링 쿼리 수정
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
Labels: sohyeon, size/XS, hotfix

#79 [FEAT] 앱 토큰에 맞춰 변환, 쿠키 리프레시 토큰
  src/main/java/org/sopt/makers/operation/controller/AdminController.java
  src/main/java/org/sopt/makers/operation/dto/admin/RefreshResponseDTO.java
  src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenProvider.java
  src/main/java/org/sopt/makers/operation/service/AdminService.java
  src/main/java/org/sopt/makers/operation/service/AdminServiceImpl.java
Labels: yongtaek, size/L, feat, fix

#83 [FEAT] 출석 기능
  src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/controller/AppController.java
  src/main/java/org/sopt/makers/operation/controller/ExceptionController.java
  src/main/java/org/sopt/makers/operation/controller/LectureController.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureCurrentRoundResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/SubLecture.java
  src/main/java/org/sopt/makers/operation/exception/SubLectureException.java
  src/main/java/org/sopt/makers/operation/repository/lecture/SubLectureRepository.java
  src/main/java/org/sopt/makers/operation/service/AttendanceService.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureService.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: yongtaek, size/L, feat

#85 [FIX] 세션 상세 조회 API 분리
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/controller/AttendanceController.java
  src/main/java/org/sopt/makers/operation/controller/LectureController.java
  src/main/java/org/sopt/makers/operation/dto/attendance/MemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/AttendanceRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/SubLecture.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/AttendanceService.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureService.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
  src/main/java/org/sopt/makers/operation/util/Generation32.java
Labels: sohyeon, size/L, fix

#91 [REFACT] 로그인, 리프레시 service 작동 방식, 쿠키 모듈화
  src/main/java/org/sopt/makers/operation/controller/AdminController.java
  src/main/java/org/sopt/makers/operation/dto/admin/LoginResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/admin/RefreshResponseDTO.java
  src/main/java/org/sopt/makers/operation/service/AdminService.java
  src/main/java/org/sopt/makers/operation/service/AdminServiceImpl.java
  src/main/java/org/sopt/makers/operation/util/Cookie.java
Labels: yongtaek, size/L, fix

#92 [REFACT] 쿼리 최적화
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceMemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/MemberInfo.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepository.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
Labels: size/L

#97 [FIX] 출석하기 케이스 반환값 추가, 로직 수정
  src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/controller/app/AppLectureController.java
  src/main/java/org/sopt/makers/operation/controller/app/AppMemberController.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/SubLecture.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepository.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/lecture/SubLectureRepository.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberRepository.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/MemberServiceImpl.java
Labels: yongtaek, size/L, fix

#100 [FIX] 출석 종료 기능 수정: 설명 워딩 추가, 예외 처리 추가
  src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
  src/main/java/org/sopt/makers/operation/controller/web/LectureController.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: sohyeon, size/XS, fix

#101 [FIX] 현재 세미나 감추기, 프로그레스바 #98
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureGetResponseVO.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: size/M, yongtaek, fix

#104 [FIX] UTC 관련 이슈 수정
  src/main/java/org/sopt/makers/operation/entity/BaseEntity.java
Labels: sohyeon, size/XS, fix

#106 [ADD] 출석 결과 정보 추가
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceMemberResponseDTO.java
Labels: sohyeon, size/XS, add

#108 [ DEPLOY] 실서버 배포
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceMemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
Labels: size/XS
