Repository sopt-makers/sopt-operation-backend, pull requests merged in 2023-12, with the labels that each got.

#202 [CHORE] 실서버 배포
  .gitignore
  README.md
  src/main/java/org/sopt/makers/operation/controller/ExceptionController.java
  src/main/java/org/sopt/makers/operation/dto/admin/LoginResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/MemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LecturesResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/AdminStatus.java
  src/main/java/org/sopt/makers/operation/entity/Role.java
  src/main/java/org/sopt/makers/operation/entity/alarm/Alarm.java
  src/main/java/org/sopt/makers/operation/service/AlarmServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
  src/main/resources/console-appender.xml
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/logback-spring.xml
Labels: size/L

#206 [ADD] 응답 데이터 총 개수 추가
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmsResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendancesResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/member/MembersResponseDTO.java
  src/main/java/org/sopt/makers/operation/repository/alarm/AlarmCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/alarm/AlarmRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/AlarmServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/AttendanceService.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/MemberService.java
  src/main/java/org/sopt/makers/operation/service/MemberServiceImpl.java
Labels: sohyeon, size/L, add

#205 [FIX] 포트 포워딩 삭제
  scripts/switch.sh
Labels: yongtaek, size/XS, feat

#210 [FIX] 외부 API 인터페이스 분리
  src/main/java/org/sopt/makers/operation/config/RestTemplateConfig.java
  src/main/java/org/sopt/makers/operation/controller/web/AlarmController.java
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmSenderDTO.java
  src/main/java/org/sopt/makers/operation/external/api/AlarmSender.java
  src/main/java/org/sopt/makers/operation/external/api/AlarmSenderImpl.java
  src/main/java/org/sopt/makers/operation/external/api/PlayGroundServer.java
  src/main/java/org/sopt/makers/operation/external/api/PlayGroundServerImpl.java
  src/main/java/org/sopt/makers/operation/service/AlarmService.java
  src/main/java/org/sopt/makers/operation/service/AlarmServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: sohyeon, size/L, fix

#215 [ADD] PR 이어받아 추가 작업
  src/main/java/org/sopt/makers/operation/dto/schedule/SchedulesResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/schedule/Schedule.java
  src/main/java/org/sopt/makers/operation/repository/schedule/ScheduleCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/schedule/ScheduleRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/ScheduleServiceImpl.java
Labels: sohyeon, size/L, add

#214 [FEAT] 일정 리스트 조회 기능
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/controller/app/AppScheduleController.java
  src/main/java/org/sopt/makers/operation/dto/schedule/SchedulesResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/schedule/Schedule.java
  src/main/java/org/sopt/makers/operation/repository/schedule/ScheduleCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/schedule/ScheduleRepository.java
  src/main/java/org/sopt/makers/operation/repository/schedule/ScheduleRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/ScheduleService.java
  src/main/java/org/sopt/makers/operation/service/ScheduleServiceImpl.java
Labels: size/L, feat

#217 [FIX] health check 소요 시간 추가
  scripts/health_check.sh
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/controller/app/AppScheduleController.java
  src/main/java/org/sopt/makers/operation/dto/schedule/SchedulesResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/schedule/Schedule.java
  src/main/java/org/sopt/makers/operation/repository/schedule/ScheduleCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/schedule/ScheduleRepository.java
  src/main/java/org/sopt/makers/operation/repository/schedule/ScheduleRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/ScheduleService.java
  src/main/java/org/sopt/makers/operation/service/ScheduleServiceImpl.java
Labels: bug, size/L
