Repository sopt-makers/sopt-operation-backend, pull requests merged in 2023-10, with the labels that each got.

#165 [ADD] 세션 상세 조회: 응답 값 추가
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureDetailResponseDTO.java
Labels: sohyeon, size/XS, add

#167 [REFACT] 출석 기능 리팩토링
  src/main/java/org/sopt/makers/operation/controller/web/AttendanceController.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendUpdateRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceMemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/MemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/SubAttendanceUpdateRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/SubAttendanceUpdateResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/Attendance.java
  src/main/java/org/sopt/makers/operation/entity/Member.java
  src/main/java/org/sopt/makers/operation/entity/SubAttendance.java
  src/main/java/org/sopt/makers/operation/entity/lecture/Lecture.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/AttendanceService.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
  src/main/java/org/sopt/makers/operation/util/Generation32.java
Labels: sohyeon, size/L, fix

#168 [CHORE] prod 서버 배포
  src/main/java/org/sopt/makers/operation/controller/web/AttendanceController.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendUpdateRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceMemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/MemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/SubAttendanceUpdateRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/SubAttendanceUpdateResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureDetailResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/Attendance.java
  src/main/java/org/sopt/makers/operation/entity/Member.java
  src/main/java/org/sopt/makers/operation/entity/SubAttendance.java
  src/main/java/org/sopt/makers/operation/entity/lecture/Lecture.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/AttendanceService.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
  src/main/java/org/sopt/makers/operation/util/Generation32.java
Labels: size/L

#170 [CHORE] Entity 추가 설계
  src/main/java/org/sopt/makers/operation/converter/LongListConverter.java
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/member/MemberRequestDTO.java
  src/main/java/org/sopt/makers/operation/entity/Gender.java
  src/main/java/org/sopt/makers/operation/entity/Member.java
  src/main/java/org/sopt/makers/operation/entity/alarm/Alarm.java
  src/main/java/org/sopt/makers/operation/entity/alarm/Attribute.java
  src/main/java/org/sopt/makers/operation/entity/alarm/Status.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
Labels: sohyeon, chore, size/L

#173 [FEAT] 알림 어드민 API 개발
  src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/controller/web/AlarmController.java
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmsResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/alarm/Alarm.java
  src/main/java/org/sopt/makers/operation/repository/alarm/AlarmCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/alarm/AlarmRepository.java
  src/main/java/org/sopt/makers/operation/repository/alarm/AlarmRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/AlarmService.java
  src/main/java/org/sopt/makers/operation/service/AlarmServiceImpl.java
Labels: sohyeon, size/L, feat

#177 [ADD] 세션 종료 후 알림 발송 추가
  src/main/java/org/sopt/makers/operation/service/AlarmService.java
  src/main/java/org/sopt/makers/operation/service/AlarmServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: sohyeon, size/S, add

#179 [FIX] 컨버터 수정
  src/main/java/org/sopt/makers/operation/converter/StringListConverter.java
  src/main/java/org/sopt/makers/operation/entity/alarm/Alarm.java
Labels: sohyeon, size/M, fix

#175 [FEAT] 알림 어드민 API 개발 #173
  src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/controller/ExceptionController.java
  src/main/java/org/sopt/makers/operation/controller/web/AlarmController.java
  src/main/java/org/sopt/makers/operation/converter/StringListConverter.java
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmInactiveListResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmSendRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmSendResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/alarm/Alarm.java
  src/main/java/org/sopt/makers/operation/exception/AlarmException.java
  src/main/java/org/sopt/makers/operation/service/AlarmService.java
  src/main/java/org/sopt/makers/operation/service/AlarmServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: yongtaek, size/L, feat

#180 [CHORE] prod 서버 배포
  src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/controller/ExceptionController.java
  src/main/java/org/sopt/makers/operation/controller/web/AlarmController.java
  src/main/java/org/sopt/makers/operation/converter/StringListConverter.java
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmInactiveListResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmSendRequestDTO.java
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmSendResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmsResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/member/MemberRequestDTO.java
  src/main/java/org/sopt/makers/operation/entity/Gender.java
  src/main/java/org/sopt/makers/operation/entity/Member.java
  src/main/java/org/sopt/makers/operation/entity/alarm/Alarm.java
  src/main/java/org/sopt/makers/operation/entity/alarm/Attribute.java
  src/main/java/org/sopt/makers/operation/entity/alarm/Status.java
  src/main/java/org/sopt/makers/operation/exception/AlarmException.java
  src/main/java/org/sopt/makers/operation/repository/alarm/AlarmCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/alarm/AlarmRepository.java
  src/main/java/org/sopt/makers/operation/repository/alarm/AlarmRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/AlarmService.java
  src/main/java/org/sopt/makers/operation/service/AlarmServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: size/XL

#182 [FIX] 요일 값 수정
  src/main/java/org/sopt/makers/operation/controller/ScheduleController.java
Labels: sohyeon, size/XS, fix

#183 [CHORE] SP1 prod 서버 반영
  src/main/java/org/sopt/makers/operation/controller/ScheduleController.java
Labels: size/XS
