Repository sopt-makers/sopt-operation-backend, pull requests merged in 2023-11, with the labels that each got.

#184 [CHORE] 실서버 배포
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: size/XS

#185 [CHORE] 실서버 배포
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmResponseDTO.java
Labels: size/XS

#188 [FIX] 알림 생성 : null 처리 분리
  src/main/java/org/sopt/makers/operation/entity/alarm/Alarm.java
Labels: sohyeon, size/XS, fix

#190 [FIX] 알림 어드민 발송 필터 및 전송 시간 에러 수정
  src/main/java/org/sopt/makers/operation/entity/alarm/Alarm.java
  src/main/java/org/sopt/makers/operation/service/AlarmServiceImpl.java
Labels: bug, yongtaek, size/S

#192 [ADD] 응답 데이터 추가
  src/main/java/org/sopt/makers/operation/dto/attendance/MemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LecturesResponseDTO.java
Labels: sohyeon, size/XS, add

#194 [ADD] 생성 기준 기수 칼럼 추가
  src/main/java/org/sopt/makers/operation/dto/alarm/AlarmRequestDTO.java
  src/main/java/org/sopt/makers/operation/entity/alarm/Alarm.java
Labels: sohyeon, size/XS, add

#196 [FIX] 알림 발송 대상 회원 플그 id null 처리 추가
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: sohyeon, size/XS, fix

#198 [ADD] 로그인시 권한 반환 추가
  src/main/java/org/sopt/makers/operation/dto/admin/LoginResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/AdminStatus.java
Labels: yongtaek, size/S, feat

#199 [TEST] CD-TEST
  README.md
Labels: size/XS
