Repository sopt-makers/sopt-operation-backend, pull requests merged in 2023-03, with the labels that each got.

#4 [CHORE] Issue, Pull Request 템플릿 생성
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/S

#6 [FIX]: healthCheck root 경로로 변경
  scripts/health_check.sh
  src/main/java/org/sopt/makers/operation/controllers/HealthCheckController.java
Labels: size/XS

#11 [FEAT] 출석 관련 Entity 설계 및 생성
  src/main/java/org/sopt/makers/operation/controller/HealthCheckController.java
  src/main/java/org/sopt/makers/operation/entity/Attendance.java
  src/main/java/org/sopt/makers/operation/entity/AttendanceStatus.java
  src/main/java/org/sopt/makers/operation/entity/Part.java
  src/main/java/org/sopt/makers/operation/entity/Session.java
  src/main/java/org/sopt/makers/operation/entity/SubAttendance.java
  src/main/java/org/sopt/makers/operation/entity/SubSession.java
Labels: sohyeon, size/L, feat

#14 [FIX] Entity 추가 설정
  src/main/java/org/sopt/makers/operation/config/JpaAuditingConfig.java
  src/main/java/org/sopt/makers/operation/entity/BaseEntity.java
  src/main/java/org/sopt/makers/operation/entity/Session.java
  src/main/java/org/sopt/makers/operation/entity/SubAttendance.java
Labels: sohyeon, size/M, fix

#16 [FIX] 필드명 오류 수정
  src/main/java/org/sopt/makers/operation/entity/SubSession.java
Labels: yongtaek, size/XS, fix
