Repository sopt-makers/sopt-operation-backend, pull requests merged in 2023-09, with the labels that each got.

#144 [FEAT] 회원 등록 API
  src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/controller/InternalOpenApiController.java
  src/main/java/org/sopt/makers/operation/controller/app/AppMemberController.java
  src/main/java/org/sopt/makers/operation/dto/member/MemberRequestDTO.java
  src/main/java/org/sopt/makers/operation/entity/Member.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberRepository.java
  src/main/java/org/sopt/makers/operation/service/MemberService.java
  src/main/java/org/sopt/makers/operation/service/MemberServiceImpl.java
Labels: sohyeon, size/L, feat

#146 [CHORE] production 배포
  src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
  src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
  src/main/java/org/sopt/makers/operation/config/SwaggerConfig.java
  src/main/java/org/sopt/makers/operation/controller/InternalOpenApiController.java
  src/main/java/org/sopt/makers/operation/controller/app/AppMemberController.java
  src/main/java/org/sopt/makers/operation/controller/web/AttendanceController.java
  src/main/java/org/sopt/makers/operation/dto/member/MemberRequestDTO.java
  src/main/java/org/sopt/makers/operation/entity/Member.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberRepository.java
  src/main/java/org/sopt/makers/operation/security/config/SecurityConfig.java
  src/main/java/org/sopt/makers/operation/service/MemberService.java
  src/main/java/org/sopt/makers/operation/service/MemberServiceImpl.java
Labels: sohyeon, chore, size/L

#148 [DEL] 스웨거 제한
  src/main/java/org/sopt/makers/operation/security/config/SecurityConfig.java
Labels: sohyeon, chore, size/XS

#136 [FIX] 현재 세션 가져오기 성능 최적화
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureGetResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureGetResponseVO.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: yongtaek, size/L, fix

#138 [FIX] 단일 라운드 조회 리팩토링
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: size/M, yongtaek, fix

#150 [FIX] Gender 데이터 생략
  src/main/java/org/sopt/makers/operation/dto/member/MemberRequestDTO.java
  src/main/java/org/sopt/makers/operation/entity/Member.java
Labels: sohyeon, size/XS, fix

#154 [DOCS] PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: sohyeon, chore, size/XS, add

#152 [FEAT] 출석 자동 종료 스케줄러
  src/main/java/org/sopt/makers/operation/controller/ScheduleController.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureService.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: sohyeon, size/M, feat

#156 [ADD] 회원 리스트 조회 페이지네이션 추가
  src/main/java/org/sopt/makers/operation/controller/web/MemberController.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/MemberService.java
  src/main/java/org/sopt/makers/operation/service/MemberServiceImpl.java
Labels: sohyeon, size/M, add

#158 [CHORE] production 서버 배포
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/org/sopt/makers/operation/controller/ScheduleController.java
  src/main/java/org/sopt/makers/operation/controller/web/MemberController.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureGetResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureGetResponseVO.java
  src/main/java/org/sopt/makers/operation/dto/member/MemberRequestDTO.java
  src/main/java/org/sopt/makers/operation/entity/Member.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/lecture/LectureRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/LectureService.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/MemberService.java
  src/main/java/org/sopt/makers/operation/service/MemberServiceImpl.java
Labels: sohyeon, chore, size/L

#161 [DEL] 플그 id Unique 속성 삭제
  src/main/java/org/sopt/makers/operation/entity/Member.java
Labels: sohyeon, size/XS, fix

#163 [FIX] 앱 토큰 유저 정보 획득시 현재 기수 필터링 되지 않는 오류
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/repository/member/MemberRepository.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
  src/main/java/org/sopt/makers/operation/service/MemberServiceImpl.java
Labels: yongtaek, size/S, fix
