Repository sopt-makers/sopt-operation-backend, pull requests merged in 2023-05, with the labels that each got.

#111 [ADD] 출석 관련 세션 상태 데이터 추가
  src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
  src/main/java/org/sopt/makers/operation/controller/web/LectureController.java
  src/main/java/org/sopt/makers/operation/dto/lecture/LectureResponseDTO.java
  src/main/java/org/sopt/makers/operation/entity/SubLecture.java
  src/main/java/org/sopt/makers/operation/entity/lecture/Lecture.java
  src/main/java/org/sopt/makers/operation/entity/lecture/LectureStatus.java
  src/main/java/org/sopt/makers/operation/service/LectureService.java
  src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
Labels: sohyeon, size/L, add

#115 [FIX] 쿼리 최적화 리팩토링 (출석 리스트 조회)
  src/main/java/org/sopt/makers/operation/controller/web/AttendanceController.java
  src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceMemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/dto/attendance/LectureInfo.java
  src/main/java/org/sopt/makers/operation/dto/attendance/MemberInfo.java
  src/main/java/org/sopt/makers/operation/dto/attendance/MemberResponseDTO.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
  src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
  src/main/java/org/sopt/makers/operation/service/AttendanceService.java
  src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
Labels: sohyeon, size/L, fix

#116 쿠키설정, 리프레시 응답코드
  src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
  src/main/java/org/sopt/makers/operation/security/config/SecurityConfig.java
  src/main/java/org/sopt/makers/operation/security/jwt/JwtAuthenticationFilter.java
  src/main/java/org/sopt/makers/operation/security/jwt/JwtExceptionFilter.java
  src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenProvider.java
  src/main/java/org/sopt/makers/operation/util/Cookie.java
Labels: size/L, feat
