Repository sopt-makers/sopt-operation-backend, pull requests merged in 2024-02, with the labels that each got.

#232 [REFACTOR] auth 모듈 분리
  operation-api/build.gradle
  operation-auth/build.gradle
  operation-auth/src/main/java/org/sopt/makers/operation/authentication/AdminAuthentication.java
  operation-auth/src/main/java/org/sopt/makers/operation/config/SecurityConfig.java
  operation-auth/src/main/java/org/sopt/makers/operation/filter/JwtAuthenticationFilter.java
  operation-auth/src/main/java/org/sopt/makers/operation/filter/JwtExceptionFilter.java
  operation-auth/src/main/java/org/sopt/makers/operation/jwt/JwtTokenProvider.java
  operation-auth/src/main/java/org/sopt/makers/operation/jwt/JwtTokenType.java
Labels: size/L

#241 [REFACTOR] 2차 기능 리팩토링
  operation-api/src/main/java/org/sopt/makers/operation/app/attendance/api/AppAttendanceApi.java
  operation-api/src/main/java/org/sopt/makers/operation/app/attendance/api/AppAttendanceApiController.java
  operation-api/src/main/java/org/sopt/makers/operation/app/attendance/dto/request/LectureAttendRequest.java
  operation-api/src/main/java/org/sopt/makers/operation/app/attendance/dto/response/AttendanceResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/app/attendance/dto/response/LectureAttendResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/app/attendance/service/AppAttendanceService.java
  operation-api/src/main/java/org/sopt/makers/operation/app/attendance/service/AppAttendanceServiceImpl.java
  operation-api/src/main/java/org/sopt/makers/operation/app/lecture/dto/response/LectureCurrentRoundResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/app/lecture/dto/response/TodayLectureResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/app/lecture/service/AppLectureServiceImpl.java
  operation-api/src/main/java/org/sopt/makers/operation/app/member/dto/response/AttendanceTotalResponseDTO.java
  operation-api/src/main/java/org/sopt/makers/operation/app/member/dto/response/AttendanceTotalVO.java
  operation-api/src/main/java/org/sopt/makers/operation/app/member/dto/response/MemberScoreGetResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/app/member/service/AppMemberServiceImpl.java
Labels: enhancement, size/L

#242 [FIX] 테스트 경로 추가
  operation-auth/src/main/java/org/sopt/makers/operation/config/SecurityConfig.java
  operation-auth/src/main/java/org/sopt/makers/operation/filter/JwtAuthenticationFilter.java
  scripts/health_check.sh
Labels: size/XS

#246 리드미 업데이트
  README.md
Labels: documentation, sohyeon, size/L

#226 [FIX] error, info 로그 저장 디렉토리 복구
  operation-api/src/main/resources/file-error-appender.xml
  operation-api/src/main/resources/file-info-appender.xml
Labels: bug, yongtaek, size/XS

#245 [FIX] 테스트 중 500 에러 수정 + 추가 리팩토링
  operation-api/src/main/java/org/sopt/makers/operation/app/attendance/service/AppAttendanceServiceImpl.java
  operation-api/src/main/java/org/sopt/makers/operation/app/lecture/dto/response/TodayLectureResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/app/lecture/service/AppLectureServiceImpl.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/api/AdminApiController.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/dto/request/SignUpRequest.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/dto/response/LoginResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/dto/response/RefreshResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/dto/response/SignUpResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/dto/response/TokenRefreshGetResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/service/AdminService.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/service/AdminServiceImpl.java
  operation-auth/src/main/java/org/sopt/makers/operation/filter/JwtAuthenticationFilter.java
  operation-common/src/main/java/org/sopt/makers/operation/config/ValueConfig.java
  operation-domain/build.gradle
  operation-domain/src/main/java/org/sopt/makers/operation/admin/domain/Admin.java
Labels: bug, chore, yongtaek, size/L, fix
