Repository sopt-makers/sopt-operation-backend, pull requests merged in 2024-12, with the labels that each got.

#288 [FEAT/#287] 단일 Banner 상세 조회 기능
  operation-api/build.gradle
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApi.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApiController.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/dto/response/BannerResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerService.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerServiceImpl.java
  operation-api/src/main/resources/application-test.yml
  operation-api/src/test/java/org/sopt/makers/operation/web/banner/api/BannerApiControllerTest.java
  operation-common/src/main/java/org/sopt/makers/operation/code/failure/BannerFailureCode.java
  operation-common/src/main/java/org/sopt/makers/operation/code/success/web/BannerSuccessCode.java
  operation-common/src/main/java/org/sopt/makers/operation/exception/BannerException.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/Banner.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/BannerImage.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/ContentType.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/PublishLocation.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/PublishPeriod.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/PublishStatus.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/repository/BannerRepository.java
  operation-domain/src/test/java/org/sopt/makers/operation/DatabaseCleaner.java
  operation-domain/src/test/java/org/sopt/makers/operation/banner/BannerTest.java
  operation-domain/src/test/java/org/sopt/makers/operation/banner/PublishPeriodTest.java
  operation-domain/src/test/resources/application-test.yml
Labels: feat, size/XL, donggyu

#292 [FEAT/#289] 배너 이미지 pre-sigend url 조회 및 배너 생성 API 구현
  operation-api/src/main/java/org/sopt/makers/operation/common/handler/ErrorHandler.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApi.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApiController.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/dto/request/BannerRequest.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/dto/response/BannerResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerService.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerServiceImpl.java
  operation-api/src/main/resources/application-dev.yml
  operation-api/src/main/resources/application-test.yml
  operation-api/src/test/java/org/sopt/makers/operation/web/banner/api/BannerApiControllerTest.java
  operation-common/src/main/java/org/sopt/makers/operation/code/failure/BannerFailureCode.java
  operation-common/src/main/java/org/sopt/makers/operation/code/failure/ExternalFailureCode.java
  operation-common/src/main/java/org/sopt/makers/operation/code/success/web/BannerSuccessCode.java
  operation-common/src/main/java/org/sopt/makers/operation/config/ValueConfig.java
  operation-common/src/main/java/org/sopt/makers/operation/exception/ExternalException.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/Banner.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/BannerImage.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/ContentType.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/ImageExtension.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/ImageType.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/PublishPeriod.java
  operation-external/build.gradle
  operation-external/src/main/java/org/sopt/makers/operation/client/s3/S3Manager.java
  operation-external/src/main/java/org/sopt/makers/operation/client/s3/S3Service.java
  operation-external/src/main/java/org/sopt/makers/operation/client/s3/S3ServiceImpl.java
Labels: size/L, feat, sungeun

#291 [FEAT/#290] 배너 삭제 & 외부 배너 조회 기능 구현
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApi.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApiController.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/dto/response/BannerResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerService.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerServiceImpl.java
  operation-api/src/test/java/org/sopt/makers/operation/web/banner/api/BannerApiControllerTest.java
  operation-common/src/main/java/org/sopt/makers/operation/code/failure/BannerFailureCode.java
  operation-common/src/main/java/org/sopt/makers/operation/code/success/web/BannerSuccessCode.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/BannerImage.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/repository/BannerRepository.java
Labels: size/L, feat

#296 [REFACTOR/#295] 배포 방식 변경
  .github/workflows/cd-dev.yml
  .github/workflows/ci.yml
  Dockerfile
  operation-api/build.gradle
  operation-domain/src/test/java/org/sopt/makers/operation/banner/BannerTest.java
  operation-domain/src/test/java/org/sopt/makers/operation/banner/PublishPeriodTest.java
Labels: size/L, refactor, donggyu
