Repository sopt-makers/sopt-operation-backend, pull requests merged in 2024-06, with the labels that each got.

#262 #261_T-10856 [feat] /token API 구현
  operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApi.java
  operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApiController.java
  operation-api/src/main/java/org/sopt/makers/operation/auth/dto/request/AccessTokenRequest.java
  operation-api/src/main/java/org/sopt/makers/operation/auth/dto/response/TokenResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/auth/service/AuthService.java
  operation-api/src/main/java/org/sopt/makers/operation/auth/service/AuthServiceImpl.java
  operation-api/src/main/java/org/sopt/makers/operation/common/config/ConcurrentHashMapConfig.java
  operation-api/src/test/java/org/sopt/makers/operation/auth/api/AuthApiControllerTest.java
  operation-api/src/test/java/org/sopt/makers/operation/auth/service/AuthServiceTest.java
  operation-api/src/test/java/org/sopt/makers/operation/jwt/JwtTokenProviderTest.java
  operation-auth/src/main/java/org/sopt/makers/operation/jwt/JwtTokenProvider.java
  operation-auth/src/main/java/org/sopt/makers/operation/jwt/JwtTokenType.java
  operation-common/src/main/java/org/sopt/makers/operation/code/failure/auth/AuthFailureCode.java
  operation-common/src/main/java/org/sopt/makers/operation/code/success/auth/AuthSuccessCode.java
Labels: feat, size/XL

#264 #263 [CHORE] Legacy Url 관련 코드 삭제
  operation-auth/src/main/java/org/sopt/makers/operation/config/SecurityConfig.java
  operation-common/src/main/java/org/sopt/makers/operation/config/ValueConfig.java
  operation-domain/src/main/java/org/sopt/makers/operation/auth/domain/TeamOAuthInfo.java
Labels: chore, size/L

#267 #266_T-10860 [feat] Security 내 SSO 기반 인증 End Point 등록
  operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApi.java
  operation-auth/src/main/java/org/sopt/makers/operation/config/SecurityConfig.java
Labels: size/XS, feat

#271 #270 [fix] /authorize 명세 수정
  operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApiController.java
  operation-api/src/main/java/org/sopt/makers/operation/auth/dto/response/AuthorizationCodeResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/auth/dto/response/RedirectUrlResponse.java
  operation-api/src/test/java/org/sopt/makers/operation/auth/api/AuthApiControllerTest.java
  operation-common/src/main/java/org/sopt/makers/operation/code/success/auth/AuthSuccessCode.java
Labels: size/M

#272 [FEAT] GET /internal/user/me API 구현
  operation-api/src/main/java/org/sopt/makers/operation/common/handler/ErrorHandler.java
  operation-api/src/main/java/org/sopt/makers/operation/common/util/CommonUtils.java
  operation-api/src/main/java/org/sopt/makers/operation/user/api/UserApi.java
  operation-api/src/main/java/org/sopt/makers/operation/user/api/UserApiController.java
  operation-api/src/main/java/org/sopt/makers/operation/user/dto/response/UserActivityInfoResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/user/dto/response/UserInfoResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/user/dto/response/UserInfosResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/user/service/UserService.java
  operation-api/src/main/java/org/sopt/makers/operation/user/service/UserServiceImpl.java
  operation-api/src/test/java/org/sopt/makers/operation/user/api/UserApiControllerTest.java
  operation-api/src/test/java/org/sopt/makers/operation/user/service/UserServiceTest.java
  operation-common/src/main/java/org/sopt/makers/operation/code/failure/UserFailureCode.java
  operation-common/src/main/java/org/sopt/makers/operation/code/success/UserSuccessCode.java
  operation-common/src/main/java/org/sopt/makers/operation/exception/ParameterDecodeCustomException.java
  operation-common/src/main/java/org/sopt/makers/operation/exception/UserException.java
  operation-domain/src/main/java/org/sopt/makers/operation/user/repository/UserRepository.java
  operation-domain/src/main/java/org/sopt/makers/operation/user/repository/history/UserGenerationHistoryRepository.java
  operation-domain/src/main/java/org/sopt/makers/operation/user/repository/identityinfo/UserIdentityInfoRepository.java
  operation-domain/src/test/java/org/sopt/makers/operation/user/repository/UserRepositoryTest.java
Labels: feat, size/XL
