Repository sopt-makers/sopt-operation-backend, pull requests merged in 2025-01, with the labels that each got.

#301 [TEST/#299] 배너 생성 컨트롤러 테스트코드 작성
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerService.java
  operation-api/src/test/java/org/sopt/makers/operation/web/banner/api/BannerApiControllerTest.java
Labels: chore, size/M, sungeun

#303 [MODIFY] transfer 한 file mv 명령에 sudo 추가
  .github/workflows/cd-dev.yml
Labels: size/S

#298 [FEAT/#297] 배너 목록 조회 기능 구현
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApi.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApiController.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/dto/response/BannerResponse.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerService.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerServiceImpl.java
  operation-api/src/main/resources/data/insert-get-banners-data.sql
  operation-api/src/test/java/org/sopt/makers/operation/web/banner/service/BannerServiceTest.java
  operation-common/src/main/java/org/sopt/makers/operation/code/failure/BannerFailureCode.java
  operation-common/src/main/java/org/sopt/makers/operation/code/success/web/BannerSuccessCode.java
  operation-common/src/main/java/org/sopt/makers/operation/config/TimeConfig.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/PublishStatus.java
  operation-domain/src/test/java/org/sopt/makers/operation/banner/BannerTest.java
Labels: size/L

#294 [FEAT/#293] 배너 수정 API 구현
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApi.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApiController.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/dto/request/BannerRequest.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerService.java
  operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerServiceImpl.java
  operation-api/src/test/java/org/sopt/makers/operation/web/banner/api/BannerApiControllerTest.java
  operation-common/src/main/java/org/sopt/makers/operation/code/success/web/BannerSuccessCode.java
  operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/Banner.java
  operation-external/src/main/java/org/sopt/makers/operation/client/s3/S3Service.java
  operation-external/src/main/java/org/sopt/makers/operation/client/s3/S3ServiceImpl.java
Labels: size/L, feat, sungeun
