Repository sopt-makers/sopt-operation-backend, pull requests merged in 2025-05, with the labels that each got.

#338 [FEAT] 비밀번호 변경 api 추가
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/api/AdminApi.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/api/AdminApiController.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/dto/request/PasswordChangeRequest.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/service/AdminService.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/service/AdminServiceImpl.java
  operation-auth/src/main/java/org/sopt/makers/operation/filter/JwtAuthenticationFilter.java
  operation-common/src/main/java/org/sopt/makers/operation/code/success/web/AdminSuccessCode.java
Labels: size/M, 🎁 feature

#339 [Merge] develop -> main 2025/05/05
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/api/AdminApi.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/api/AdminApiController.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/dto/request/PasswordChangeRequest.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/service/AdminService.java
  operation-api/src/main/java/org/sopt/makers/operation/web/admin/service/AdminServiceImpl.java
  operation-auth/src/main/java/org/sopt/makers/operation/filter/JwtAuthenticationFilter.java
  operation-common/src/main/java/org/sopt/makers/operation/code/success/web/AdminSuccessCode.java
Labels: size/M, 🎁 feature

#341 [FIX] 알림 한글 깨짐 이슈
  Dockerfile
  operation-external/src/main/java/org/sopt/makers/operation/client/alarm/InstantAlarmSender.java
Labels: size/S, 🔨 fix

#342 [Merge] develop -> main 2025/05/09
  Dockerfile
  operation-external/src/main/java/org/sopt/makers/operation/client/alarm/InstantAlarmSender.java
Labels: size/S, 🔨 fix

#345 [FIX] 알림 어드민: 활동기수 + 전체 파트로 전송 시 dev 테이블에서 존재하지 않는 Part가 존재하지 않는 문제 해결
  build.gradle
  operation-api/src/main/java/org/sopt/makers/operation/common/config/SwaggerConfig.java
Labels: size/M

#346 [FIX] 알림 서버에 즉시 알림 요청 시 body 필드명 appLink -> deepLink로 오타 수정
  operation-external/src/main/java/org/sopt/makers/operation/client/alarm/InstantAlarmSender.java
Labels: size/XS, 🔨 fix

#348 [FIX] 누락된 deepLink 리스트 추가
  operation-common/src/main/java/org/sopt/makers/operation/config/ValueConfig.java
  operation-common/src/main/java/org/sopt/makers/operation/constant/AlarmConstant.java
Labels: size/XS, 🔨 fix

#350 [FIX] 모든 알림 생성 요청에 대해 createdGeneration 저장하도록 수정
  operation-api/src/main/java/org/sopt/makers/operation/web/alarm/dto/request/AlarmInstantSendRequest.java
  operation-api/src/main/java/org/sopt/makers/operation/web/alarm/dto/request/AlarmScheduleSendRequest.java
  operation-domain/src/main/java/org/sopt/makers/operation/alarm/domain/AlarmTarget.java
Labels: size/S, 🔨 fix

#351 [Merge] develop -> main 2025/05/18
  build.gradle
  operation-api/src/main/java/org/sopt/makers/operation/common/config/SwaggerConfig.java
  operation-api/src/main/java/org/sopt/makers/operation/web/alarm/dto/request/AlarmInstantSendRequest.java
  operation-api/src/main/java/org/sopt/makers/operation/web/alarm/dto/request/AlarmScheduleSendRequest.java
  operation-common/src/main/java/org/sopt/makers/operation/config/ValueConfig.java
  operation-common/src/main/java/org/sopt/makers/operation/constant/AlarmConstant.java
  operation-domain/src/main/java/org/sopt/makers/operation/alarm/domain/AlarmTarget.java
  operation-external/src/main/java/org/sopt/makers/operation/client/alarm/InstantAlarmSender.java
Labels: size/M, 🔨 fix
